#include "actions.h"

ParserAction actionTable[] = {
    { ACTION_READY, str_ready, 0, 0 },
    { ACTION_OK, str_ok, 0, 0 },
    { ACTION_ERROR, str_error, 0, 0 },
    { ACTION_BUSY_P, str_busy_p, 0, 0 },
    { ACTION_BUSY_S, str_busy_s, 0, 0 },
    { ACTION_FAIL, str_fail, 0, 0 },
    { ACTION_SEND_OK, str_send_ok, 0, 0 },
    { ACTION_SEND_FAIL, str_send_fail, 0, 0 },
    { ACTION_WIFI_DISCONNECT, str_wifi_disconn, 0, 0 },
    { ACTION_WIFI_CONNECT, str_wifi_connect, 0, 0 },
    { ACTION_WIFI_GOTIP, str_wifi_got_ip, 0, 0 },
    { ACTION_CIFSR_STAIP, str_staip, 0, 0 },
    { ACTION_CIFSR_APIP, str_apip, 0, 0 },
    { ACTION_CIPSTAMAC, str_stamac, 0, 0 },
    { ACTION_CIPAPMAC, str_apmac, 0, 0 },
    { ACTION_CONNECT, str_connect, 1, 0 },
    { ACTION_CONNECT_FAIL, str_connect_fail, 1, 0 },
    { ACTION_CLOSED, str_closed, 1, 0 },
    { ACTION_CWLAP, str_cwlap, 0, 0 },
    { ACTION_CWJAP, str_cwjap, 0, 0 },
    { ACTION_IPD, str_ipd, 0, 0 },
    { ACTION_AT_RST, str_at_rst, 0, 0 },
    { ACTION_AT_CIFSR, str_at_cifsr, 0, 0 },
    { ACTION_AT_CWLAP, str_at_cwlap, 0, 0 },
    { ACTION_AT_VERSION, str_at_version, 0, 0 },
    { ACTION_AT_CIPSTAMAC, str_at_cipstamac, 0, 0 },
    { ACTION_PROMPT, str_prompt, 0, 0 },
};
